version: '3'

services:
  healthcheck:
    image: felipemocruha/healthcheck:${IMG_VERSION}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    deploy:
      mode: global
